# Generated by Django 3.0.3 on 2020-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartDiseaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('trestbps', models.IntegerField(blank=True, default=None, null=True)),
                ('chol', models.IntegerField(blank=True, default=None, null=True)),
                ('fbs', models.IntegerField(blank=True, default=None, null=True)),
                ('thalach', models.IntegerField(blank=True, default=None, null=True)),
                ('exang', models.IntegerField(blank=True, default=None, null=True)),
                ('oldpeak', models.FloatField(blank=True, default=None, null=True)),
                ('ca', models.IntegerField(blank=True, default=None, null=True)),
                ('cp_0', models.IntegerField(blank=True, default=None, null=True)),
                ('cp_1', models.IntegerField(blank=True, default=None, null=True)),
                ('cp_2', models.IntegerField(blank=True, default=None, null=True)),
                ('cp_3', models.IntegerField(blank=True, default=None, null=True)),
                ('slope_0', models.IntegerField(blank=True, default=None, null=True)),
                ('slope_1', models.IntegerField(blank=True, default=None, null=True)),
                ('slope_2', models.IntegerField(blank=True, default=None, null=True)),
                ('thal_0', models.IntegerField(blank=True, default=None, null=True)),
                ('thal_1', models.IntegerField(blank=True, default=None, null=True)),
                ('thal_2', models.IntegerField(blank=True, default=None, null=True)),
                ('thal_3', models.IntegerField(blank=True, default=None, null=True)),
                ('restecg_0', models.IntegerField(blank=True, default=None, null=True)),
                ('restecg_1', models.IntegerField(blank=True, default=None, null=True)),
                ('restecg_2', models.IntegerField(blank=True, default=None, null=True)),
                ('sex_0', models.IntegerField(blank=True, default=None, null=True)),
                ('sex_1', models.IntegerField(blank=True, default=None, null=True)),
                ('prediction', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeartDiseaseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=200)),
                ('tasks', models.CharField(max_length=1000)),
                ('probability', models.FloatField(blank=True, default=None, null=True)),
                ('error', models.BooleanField()),
                ('error_description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
