# Generated by Django 3.0.3 on 2020-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_auto_20200425_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtime',
            name='tasks',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtime',
            name='error_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
