# Generated by Django 3.0.3 on 2020-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malariadisease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalariaDiseaseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=200)),
                ('probability', models.FloatField(blank=True, default=None, null=True)),
                ('error', models.BooleanField()),
                ('error_description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MalariaDisease',
            new_name='MalariaDiseaseBase',
        ),
    ]
