# Generated by Django 3.0.3 on 2020-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneydisease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='age',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='al',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='ane',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='appet',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='ba',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='bgr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='bp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='bu',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='cad',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='dm',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='fbs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='hemo',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='htn',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='pc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='pcc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='pcv',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='pe',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='pot',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='rc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='sc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='sg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='sod',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='su',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kidneydiseaserequest',
            name='wc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
