# Generated by Django 3.0.3 on 2020-04-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidneydisease', '0002_auto_20200427_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kidneydiseaserequest',
            name='fbs',
        ),
    ]
