# Generated by Django 3.0.3 on 2020-04-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneydisease', '0003_remove_kidneydiseaserequest_fbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidneyDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('bp', models.FloatField(blank=True, default=None, null=True)),
                ('sg', models.FloatField(blank=True, default=None, null=True)),
                ('al', models.FloatField(blank=True, default=None, null=True)),
                ('su', models.FloatField(blank=True, default=None, null=True)),
                ('rbc', models.CharField(max_length=100)),
                ('pc', models.CharField(max_length=100)),
                ('pcc', models.CharField(max_length=100)),
                ('ba', models.CharField(max_length=100)),
                ('bgr', models.FloatField(blank=True, default=None, null=True)),
                ('bu', models.FloatField(blank=True, default=None, null=True)),
                ('sc', models.FloatField(blank=True, default=None, null=True)),
                ('sod', models.FloatField(blank=True, default=None, null=True)),
                ('pot', models.FloatField(blank=True, default=None, null=True)),
                ('hemo', models.FloatField(blank=True, default=None, null=True)),
                ('pcv', models.FloatField(blank=True, default=None, null=True)),
                ('wc', models.FloatField(blank=True, default=None, null=True)),
                ('rc', models.FloatField(blank=True, default=None, null=True)),
                ('htn', models.CharField(max_length=100)),
                ('dm', models.CharField(max_length=100)),
                ('cad', models.CharField(max_length=100)),
                ('appet', models.CharField(max_length=100)),
                ('pe', models.CharField(max_length=100)),
                ('ane', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
