# Generated by Django 3.0.3 on 2020-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiverDiseaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('gender', models.FloatField(blank=True, default=None, null=True)),
                ('total_bilirubin', models.FloatField(blank=True, default=None, null=True)),
                ('direct_bilirubin', models.FloatField(blank=True, default=None, null=True)),
                ('alkaline_phosphotase', models.FloatField(blank=True, default=None, null=True)),
                ('alamine_aminotransferase', models.FloatField(blank=True, default=None, null=True)),
                ('aspartate_aminotransferase', models.FloatField(blank=True, default=None, null=True)),
                ('total_protiens', models.FloatField(blank=True, default=None, null=True)),
                ('albumin', models.FloatField(blank=True, default=None, null=True)),
                ('albumin_and_globulin_ratio', models.FloatField(blank=True, default=None, null=True)),
                ('prediction', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiverDiseaseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=200)),
                ('probability', models.FloatField(blank=True, default=None, null=True)),
                ('error', models.BooleanField()),
                ('error_description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
