# Generated by Django 3.0.3 on 2020-04-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liverdisease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('total_bilirubin', models.FloatField(blank=True, default=None, null=True)),
                ('direct_bilirubin', models.FloatField(blank=True, default=None, null=True)),
                ('alkaline_phosphotase', models.FloatField(blank=True, default=None, null=True)),
                ('alamine_aminotransferase', models.FloatField(blank=True, default=None, null=True)),
                ('aspartate_aminotransferase', models.FloatField(blank=True, default=None, null=True)),
                ('total_protiens', models.FloatField(blank=True, default=None, null=True)),
                ('albumin', models.FloatField(blank=True, default=None, null=True)),
                ('albumin_and_globulin_ratio', models.FloatField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
